# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Prescription Status Update API
# owned by NHS Digital (https://digital.nhs.uk/)

openapi: 3.0.3
info:
  title: Prescription status notifications delivery callback API
  version: 0.0.1
  contact:
    name: Prescription Status Update API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
  description: |
    fds
          
servers:
  - url: https://sandbox.api.service.nhs.uk/notification-delivery-status-callback
    description: Sandbox
  - url: https://int.api.service.nhs.uk/notification-delivery-status-callback
    description: Integration
  - url: https://api.service.nhs.uk/notification-delivery-status-callback
    description: Production

paths:
  /:
