# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Prescription Status Update API
# owned by NHS Digital (https://digital.nhs.uk/)

openapi: 3.0.3
info:
  title: Prescription Status Update API
  version: "0.0.1"
  contact:
    name: Prescription Status Update API Support
    url: https://digital.nhs.uk/developer/help-and-support
    email: api.management@nhs.net
  description: |
    ## Overview
    The Prescription Status Update API allows dispensing suppliers to push status information about electronic prescriptions to patients on a national scale via the NHS App (and potential other third parties in the future).
    This includes letting patients know when their prescription is ready to collect.
    The overall aim of the service is to reduce burden to front line NHS services by reducing the number of routine patient queries about their prescriptions.

    ## Who can use this API
    The prescription status query API is intended for NHS England internal use only; however, the specification of the data stores will be required by dispensing suppliers so they can provide and push the information required to a central NHS data store.
        
    ## Related APIs
    The following APIs are related to the "Prescription Status Update API:
    * [Electronic Prescriptions Service](https://digital.nhs.uk/developer/api-catalogue/electronic-prescription-service-fhir): the national service for creating and dispensing prescriptions across health and social care.
    * [Prescriptions for Patients](https://digital.nhs.uk/developer/api-catalogue/prescriptions-for-patients): the national service to retrieve prescriptions data for individual patients from the Electronic Prescription Service (EPS), for use in patient-facing applications.

    ## API Status and Roadmap
    This API is [in development](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses), meaning the API will soon be available for testing via a sandbox service or an integration environment - but we expect to make breaking changes based on developer feedback.

    ## Service Level
    This API is a platinum service, meaning it is operational and supported 24 hours a day, 365 days a year.

    For more details see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir) global standard for health care data exchange, specifically to [FHIR R4 (v4.0.1)](https://hl7.org/fhir/r4/).

    It includes some country-specific FHIR extensions, which are built against FHIR UK Core, specifically [UK Core STU3 (v0.0.9)](https://simplifier.net/HL7FHIRUKCoreR4/).

    You do not need to know much about FHIR to use this API. The API only supports POST requests containing FHIR transactions.

    FHIR APIs are just RESTful APIs that follow specific rules.
    These rules mean:
    * resource names are capitalised and singular, for example `/Bundle` not `/bundle`
    * array names are singular, for example `line` not `lines` for address lines
    * data items that are country specific and not included in the FHIR global base resources are usually wrapped in an `extension` object

    There are [libraries and software development kits](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) available to help with FHIR API integration.

    ## Network Access
    This API is available on the internet.

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and Authorisation
    This API only supports [application-restricted access](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate the calling application but not the end user.

    ### Application-restricted Access
    The end user could be:

    * a healthcare worker - in which case you must ensure they are authenticated and suitably authorised locally
    * a patient - in which case you must ensure they are authenticated locally
    * not present at all - for example as part of a back end process to check NHS numbers for data flowing from one system to another


    To use this access mode, use the following security pattern:
    * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ### Errors
    We use standard HTTP status codes to show whether an API request succeeded or not.
    They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

    ## Open source
    You might find the following [open source](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#open-source) resources useful:

    | Resource | Description | Links |
    |----------|-------------|-------|
    | FHIR libraries and SDKs | Various open source libraries for integrating with FHIR APIs. | [FHIR libraries and SDKs](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) |
    | nhs-number | Python package containing utilities for NHS numbers including validity checks, normalisation and generation. | [GitHub repo](https://github.com/uk-fci/nhs-number) \| [Python Package index](https://pypi.org/project/nhs-number/) \| [Docs](https://nhs-number.uk-fci.tech/) |

    ## Environment and testing
    | Environment      | Base URL                                                            |
    |------------------|---------------------------------------------------------------------|
    | Sandbox          | `https://sandbox.api.service.nhs.uk/prescription-status-update`     |
    | Integration test | `https://int.api.service.nhs.uk/prescription-status-update`         |
    | Production       | `https://api.service.nhs.uk/prescription-status-update`             |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):

    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so it does not actually persist any updates
    * is open access, so does not allow you to test authorisation

    For details of sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):

    * is for formal integration testing
    * is stateful, so persists updates
    * includes authorisation, with [smartcard](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/nhs-smartcards-for-developers) and non-smartcard options

    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).

    ## Onboarding
    All dispenser suppliers are being asked to integrate with this new service.

x-spec-publication:
  operation-order:
    - operations:
        - method: GET
          path: /Bundle

servers:
  - url: "https://int.api.service.nhs.uk/prescription-status-update"
    description: "Integration"
  - url: "https://api.service.nhs.uk/prescription-status-update"
    description: "Production"

paths:
  /:
    post:
      operationId: prescription-status-update-bundle
      summary: Update prescription status
      description: |
        ## Overview
        Status updates to be provided on prescription items to allow users of the NHS App and Third-party App consumers to track the progress of their prescriptions and when ready to collect.
      parameters:
        - $ref: "#/components/parameters/BearerAuthorisation"
        - $ref: "#/components/parameters/RequestID"
        - $ref: "#/components/parameters/CorrelationID"
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: "#/components/schemas/UpdatePrescriptionStatusBundle"
            examples:
              ready-to-dispatch:
                summary: ready-to-dispatch
                description: A request message contains tracking status `Ready to Dispatch`.
                value:
                  $ref: examples/request-ready-to-dispatch.json
              ready-to-dispatch-partial:
                summary: ready-to-dispatch-partial
                description: A request message contains tracking status `Ready to Dispatch - Partial`.
                value:
                  $ref: examples/request-ready-to-dispatch-partial.json
              dispatched:
                summary: dispatched
                description: A request message contains tracking status `Dispatched``.
                value:
                  $ref: examples/request-dispatched.json
              ready-to-collect:
                summary: ready-to-collect
                description: A request message contains tracking status `Ready to collect`.
                value:
                  $ref: examples/request-ready-to-collect.json
              collected:
                summary: collected
                description: A request message contains tracking status `Collected`.
                value:
                  $ref: examples/request-collected.json
              multiple-items:
                summary: multiple-items
                description: A request message contains multiple items.
                value:
                  $ref: examples/request-multiple-items.json
      responses:
        "200":
          description: Successful retrieval.
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/ResponseBundle"
              examples:
                single-item:
                  description: A successful response to a UpdatePrescriptionStatus request, contains a single item.
                  value:
                    $ref: "examples/response-single-item.json"
                multiple-items:
                  description: A successful response to a UpdatePrescriptionStatus request, contains multiple items.
                  value:
                    $ref: "examples/response-multiple-items.json"

        "4XX":
          description: |
            An error occurred as follows:

            | HTTP status | Error code          | Description                                                                                                                               |
            | ----------- | ------------------- | ----------------------------------------------------------------------------------------------------------------------------------------- |
            | 400         | `value`             | Missing values or invalid JSON in request                                                                                                 |
            | 401         | `processing`        | Missing or invalid OAuth 2.0 bearer token in request                                                                                      |
            | 408         | `timeout`           | Request timed out                                                                                                                         |
            | 429         | `throttled`         | You have exceeded your application's [rate limit](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#rate-limits). |

            The error code will be included in the returned OperationOutcome (below).
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/OperationOutcome"
              example:
                  $ref: examples/error-ods-code.json
      security:
        - app-level0: []
components:
  securitySchemes:
    app-level0:
      $ref: https://proxygen.ptl.api.platform.nhs.uk/components/securitySchemes/app-level0
  parameters:
    BearerAuthorisation:
      in: header
      name: Authorization
      description: |
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis).
      required: true
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: "Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM"
    RequestID:
      in: header
      name: X-Request-ID
      required: true
      description: |
        A globally unique identifier (GUID) for the request, which we use to correlate logs through different components.
        Must be a universally unique identifier (UUID) (ideally version 4).
        Mirrored back in a response header.
      schema:
        type: string
        pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: |
        An optional ID which you can use to track transactions across multiple systems. It can have any value, but we recommend avoiding `.` characters.
        Mirrored back in a response header.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
  schemas:
    UpdatePrescriptionStatusBundle:
      type: object
      required: [entry, resourceType, type]
      description: A FHIR transaction Bundle.
      properties:
        resourceType:
          type: string
          description: FHIR resource type.
          enum: [Bundle]
        type:
          type: string
          description: Denotes that the bundle is a list of status updates to be performed as one transaction.
          enum: [transaction]
        entry:
          type: array
          description: |
            A collection of resources contained within the Bundle.
          items:
            type: object
            required: [fullUrl, resource, request]
            description: A FHIR collection Bundle.
            properties:
              fullUrl:
                type: string
                example: urn:uuid:4d70678c-81e4-4ff4-8c67-17596fd0aa46
              resource:
                $ref: "#/components/schemas/UpdatePrescriptionStatusTask"
              request:
                type: object
                required: [method, url]
                properties:
                  method:
                    type: string
                    enum: [POST]
                  url:
                    type: string
                    enum: [Task]
    UpdatePrescriptionStatusTask:
      $ref: schemas/resources/UpdatePrescriptionStatusTask.yaml
    ResponseBundle:
      $ref: "schemas/components/ResponseBundle.yaml"
    OperationOutcome:
      $ref: schemas/resources/OperationOutcome.yaml
x-nhsd-apim:
  temporary: false
  monitoring: false
  access:
  - title: Application Restricted
    grants:
      app-level0: []
  target:
    type: external
    healthcheck: /_status
    url: https://psu.dev.eps.national.nhs.uk
    security:
      type: mtls
      secret: psu-mtls-1
