ignore:
  # path-to-regexp - dependency of aws-sdk-client-mock
  - vulnerability: GHSA-j3q9-mxjg-w52f
  # This is a ReDoS vulnerability that we're not exposed to, since we don't take user regex input
  - vulnerability: GHSA-2g4f-4pwh-qvx6
    reason: "We don't take user regex input, so we're not vulnerable to this issue."
  # Axios vulnerability in checking NO_PROXY rules, which we don't use
  - vulnerability: GHSA-3p68-rc4w-qgx5
    reason: "We don't use NO_PROXY rules, so we're not vulnerable to this issue."
  - vulnerability: GHSA-j965-2qgj-vjmq
    reason: "We use v3 packages already, so we're not vulnerable to this issue."
