vulnerabilities:
  - id: CVE-2026-25128
    statement: fast-xml-parser vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb
    expired_at: 2026-03-01
  - id: CVE-2026-25547
    statement:  isaacs/brace-expansion vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb
    expired_at: 2026-03-01
  - id: CVE-2026-26278
    statement:  fast-xml-parser vulnerability accepted as risk - dependency of aws-sdk/client-dynamodb and redocly
    expired_at: 2026-04-01
  - id: CVE-2026-26996
    statement:  minimatch vulnerability accepted as risk - dependency of various packages
    expired_at: 2026-04-01
  - id: CVE-2026-27903
    statement:  minimatch vulnerability accepted as risk - dependency of various packages
    expired_at: 2026-04-01
  - id: CVE-2026-27904
    statement:  minimatch vulnerability accepted as risk - dependency of various packages
    expired_at: 2026-04-01
  - id: CVE-2026-25547
    statement:  brace-expansion vulnerability accepted as risk - dependency of various packages
    expired_at: 2026-04-01
