AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU Cloudwatch alarms and related resources

Parameters:
  StackName:
    Type: String
    Default: none

  GetStatusUpdatesFunctionName:
    Type: String
    Default: none

Resources:
  GetStatusUpdatesErrorsLogsMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterName: GetStatusUpdatesErrors
      FilterPattern: !Sub '{ ($.level = "ERROR") && ($.function_name = "${GetStatusUpdatesFunctionName}") }'
      LogGroupName:
        Fn::ImportValue: !Sub ${StackName}:functions:${GetStatusUpdatesFunctionName}:LambdaLogGroupName
      MetricTransformations:
        - MetricNamespace: LambdaLogFilterMetrics
          MetricName: ErrorCount
          MetricValue: 1
          Unit: Count
          Dimensions:
            - Key: function_name
              Value: !Ref GetStatusUpdatesFunctionName

  GetStatusUpdatesErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Get Status Updates Lambda Errors
      AlarmName: !Sub ${StackName}_GetStatusUpdatesErrors
      Namespace: LambdaLogFilterMetrics
      MetricName: GetStatusUpdatesErrorCount
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn

  GetStatusUpdatesUnhandledErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Get Status Updates lambda Unhandled Errors
      AlarmName: !Sub ${StackName}_GetStatusUpdatesUnhandledErrors
      Namespace: Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetStatusUpdatesFunctionName
      Period: 60 #seconds
      EvaluationPeriods: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Unit: Count
      ActionsEnabled: true
      AlarmActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      InsufficientDataActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
      OKActions:
        - !ImportValue lambda-resources:SlackAlertsSnsTopicArn
