AWSTemplateFormatVersion: "2010-09-09"
Resources:
  NotifyCallbackAppName:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The APIM application name used when calculating the signature for the notify callback
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: changeMe
      Name: !Sub "${AWS::StackName}-Application-Name"

  NotifyCallbackApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: The API key used when calculating the signature for the notify callback
      KmsKeyId: !ImportValue account-resources:SecretsKMSKeyAlias
      SecretString: changeMe
      Name: !Sub "${AWS::StackName}-API-Key"

Outputs:
  NotifyCallbackAppName:
    Description: The APIM application name used when calculating the signature for the notify callback
    Value: !GetAtt NotifyCallbackAppName.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "NotifyCallbackAppName"]]

  NotifyCallbackApiKey:
    Description: The API key used when calculating the signature for the notify callback
    Value: !GetAtt NotifyCallbackApiKey.Id
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "NotifyCallbackApiKey"]]
