AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  StackName:
    Type: String
    Default: none

Resources:
  PSUSecretsKMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: PSUSecretsKeyPolicy
        Statement:
          - Sid: EnableIAMUserPermissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: Enable read only decrypt
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:DescribeKey
              - kms:Decrypt
            Resource: "*"
            Condition:
              ArnLike:
                aws:PrincipalArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/${AWS::Region}/AWSReservedSSO_ReadOnly*"

  PSUSecretsKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${StackName}-PSUSecretsKMSKey
      TargetKeyId: !Ref PSUSecretsKMSKey

  UsePSUSecretsKMSKeyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${StackName}-UsePSUSecretsKMSKey
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowKmsForSecretsEncryption
            Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:ReEncrypt*
              - kms:Decrypt
            Resource: !GetAtt PSUSecretsKMSKey.Arn

  SQSSaltSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-SqsSaltSecret
      Description: Auto-generated salt for SQS_SALT
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: salt
        PasswordLength: 32
        ExcludePunctuation: true

  PSUNotifyKIDSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-PSU-Notify-KID
      Description: The id of the key (KID) used to sign JWT to NHS Notify and sent in the header
      KmsKeyId: !Ref PSUSecretsKMSKey

  PSUNotifyPrivateKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-PSU-Notify-PrivateKey
      Description: RSA private key (PEM) for signing JWT to NHS Notify
      KmsKeyId: !Ref PSUSecretsKMSKey

  PSUNotifyApplicationIDSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-PSU-Notify-Application-ID
      Description: The application ID for the DoS application to use when sending notifications to NHS Notify (e.g. bd492cde-b67e-487b-97fd-44b7414c8e95)
      KmsKeyId: !Ref PSUSecretsKMSKey

  PSUNotifyAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${StackName}-PSU-Notify-API-Key
      Description: API Key for NHS Notify
      KmsKeyId: !Ref PSUSecretsKMSKey

  GetSQSSaltSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading secret parameters"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref SQSSaltSecret

  GetPSUSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading PSU secret parameters"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref PSUNotifyKIDSecret
              - !Ref PSUNotifyPrivateKeySecret
              - !Ref PSUNotifyApplicationIDSecret
              - !Ref PSUNotifyAPIKeySecret

Outputs:
  SQSSaltSecret:
    Description: The name of the randomly generated SQS salt secret
    Value: !Ref SQSSaltSecret
    Export:
      Name: !Sub ${StackName}-SQSSaltSecret

  PSUNotifyKIDSecret:
    Description: The name of the PSU Notify KID secret
    Value: !Ref PSUNotifyKIDSecret
    Export:
      Name: !Sub ${StackName}-PSU-Notify-KID

  PSUNotifyPrivateKeySecret:
    Description: The name of the PSU Notify Private Key secret
    Value: !Ref PSUNotifyPrivateKeySecret
    Export:
      Name: !Sub ${StackName}-PSU-Notify-PrivateKey

  PSUNotifyApplicationIDSecret:
    Description: The name of the PSU Notify Application ID secret
    Value: !Ref PSUNotifyApplicationIDSecret
    Export:
      Name: !Sub ${StackName}-PSU-Notify-Application-ID

  PSUNotifyAPIKeySecret:
    Description: The name of the PSU Notify API Key secret
    Value: !Ref PSUNotifyAPIKeySecret
    Export:
      Name: !Sub ${StackName}-PSU-Notify-API-Key

  GetPSUSecretPolicy:
    Description: ARN of policy granting permission to read secrets
    Value: !Ref GetPSUSecretPolicy
    Export:
      Name: !Sub ${StackName}-GetPSUSecretPolicy

  GetSQSSaltSecretPolicy:
    Description: ARN of policy granting permission to read the SQS salt secret
    Value: !Ref GetSQSSaltSecretPolicy
    Export:
      Name: !Sub ${StackName}-GetSQSSaltSecretPolicy

  UsePSUSecretsKMSKeyPolicyArn:
    Description: ARN of managed policy granting PSU secrets KMS usage
    Value: !Ref UsePSUSecretsKMSKeyPolicy
    Export:
      Name: !Sub ${StackName}-UsePSUSecretsKMSKeyPolicyArn
