AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Scheduler to trigger NHSNotifyLambda every minute

Parameters:
  StackName:
    Type: String
  NHSNotifyLambdaArn:
    Type: String
    Description: The ARN of the NHSNotifyLambda function

Resources:
  NHSNotifyScheduler:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${StackName}-NHSNotifySchedulerRule"
      ScheduleExpression: "rate(1 minute)"
      State: ENABLED
      Targets:
        - Arn: !Ref NHSNotifyLambdaArn
          Id: "NHSNotifyLambdaTarget"

  NHSNotifyLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NHSNotifyLambdaArn
      Action: "lambda:InvokeFunction"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NHSNotifyScheduler.Arn

Outputs:
  SchedulerRuleName:
    Description: Name of the scheduler rule triggering NHSNotifyLambda
    Value: !Ref NHSNotifyScheduler
  SchedulerRuleArn:
    Description: ARN of the scheduler rule triggering NHSNotifyLambda
    Value: !GetAtt NHSNotifyScheduler.Arn
