AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU DynamoDB tables and related resources

Parameters:
  StackName:
    Type: String
    Default: none

Resources:
  PrescriptionStatusUpdatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${StackName}-PrescriptionStatusUpdates
      AttributeDefinitions:
        - AttributeName: TaskID
          AttributeType: S
        - AttributeName: PrescriptionID
          AttributeType: S
        - AttributeName: PatientNHSNumber
          AttributeType: S
        - AttributeName: PharmacyODSCode
          AttributeType: S
      KeySchema:
        - AttributeName: PrescriptionID
          KeyType: HASH
        - AttributeName: TaskID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - IndexName: PharmacyODSCodePrescriptionIDIndex
          KeySchema:
            - AttributeName: PharmacyODSCode
              KeyType: HASH
            - AttributeName: PrescriptionID
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - PatientNHSNumber
              - LineItemID
              - TerminalStatus
              - LastModified
              - Status
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        - IndexName: PatientNHSNumberIndex
          KeySchema:
            - AttributeName: PatientNHSNumber
              KeyType: HASH
          Projection:
            NonKeyAttributes:
              - LineItemID
              - TerminalStatus
              - LastModified
              - Status
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  PrescriptionStatusUpdatesResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamodb_resources.yaml
      Parameters:
        StackName: !Ref StackName
        TableName: !Ref PrescriptionStatusUpdatesTable
        TableArn: !GetAtt PrescriptionStatusUpdatesTable.Arn

Outputs:
  PrescriptionStatusUpdatesTableName:
    Description: PrescriptionStatusUpdates table name
    Value: !Ref PrescriptionStatusUpdatesTable

  PrescriptionStatusUpdatesTableArn:
    Description: PrescriptionStatusUpdates table arn
    Value: !GetAtt PrescriptionStatusUpdatesTable.Arn
