AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU stateful resources

Parameters:
  EnableDynamoDBAutoScaling:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  EnableBackup:
    Type: String
    Default: "False"
    AllowedValues:
      - "True"
      - "False"

  EnableNotificationsInternal:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnableNotificationsExternal:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  EnabledSiteODSCodesValue:
    Type: String
    Default: " "

  EnabledSystemsValue:
    Type: String
    Default: " "

  EnabledSupplierApplicationIDsValue:
    Type: String
    Default: " "

  BlockedSiteODSCodesValue:
    Type: String
    Default: " "

  NotifyRoutingPlanIDValue:
    Type: String
    Default: " "

  NotifyAPIBaseURLValue:
    Type: String
    Default: " "

  TestPresciptionsParamValue1:
    Type: String
    Default: PLACEHOLDER

  TestPresciptionsParamValue2:
    Type: String
    Default: PLACEHOLDER

  TestPresciptionsParamValue3:
    Type: String
    Default: PLACEHOLDER

  TestPresciptionsParamValue4:
    Type: String
    Default: PLACEHOLDER

Resources:
  Secrets:
    Type: AWS::Serverless::Application
    Properties:
      Location: secrets/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName

  Parameters:
    Type: AWS::Serverless::Application
    Properties:
      Location: parameters/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableNotificationsInternalValue: !Ref EnableNotificationsInternal
        EnableNotificationsExternalValue: !Ref EnableNotificationsExternal
        EnabledSiteODSCodesValue: !Ref EnabledSiteODSCodesValue
        EnabledSystemsValue: !Ref EnabledSystemsValue
        EnabledSupplierApplicationIDsValue: !Ref EnabledSupplierApplicationIDsValue
        BlockedSiteODSCodesValue: !Ref BlockedSiteODSCodesValue
        NotifyRoutingPlanIDValue: !Ref NotifyRoutingPlanIDValue
        NotifyAPIBaseURLValue: !Ref NotifyAPIBaseURLValue
        TestPresciptionsParamValue1: !Ref TestPresciptionsParamValue1
        TestPresciptionsParamValue2: !Ref TestPresciptionsParamValue2
        TestPresciptionsParamValue3: !Ref TestPresciptionsParamValue3
        TestPresciptionsParamValue4: !Ref TestPresciptionsParamValue4

  Tables:
    Type: AWS::Serverless::Application
    Properties:
      Location: tables/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableDynamoDBAutoScaling: !Ref EnableDynamoDBAutoScaling
        EnableBackup: !Ref EnableBackup

  Messaging:
    Type: AWS::Serverless::Application
    Properties:
      Location: messaging/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
