AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU state machines and related resources

Parameters:
  StackName:
    Type: String
    Default: none

  UpdatePrescriptionStatusFunctionName:
    Type: String
    Default: none

  UpdatePrescriptionStatusFunctionArn:
    Type: String
    Default: none

  ConvertRequestToFhirFormatFunctionName:
    Type: String
    Default: none

  ConvertRequestToFhirFormatFunctionArn:
    Type: String
    Default: none

  LogRetentionInDays:
    Type: Number

  EnableSplunk:
    Type: String

  FihrValidatorStackName:
    Type: String
    Default: fhir-validator

Resources:
  UpdatePrescriptionStatusStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-UpdatePrescriptionStatus
      Type: EXPRESS
      Role: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: UpdatePrescriptionStatusStateMachine.asl.json
      DefinitionSubstitutions:
        FhirValidationFunctionArn: !Join
          - ":"
          - - Fn::ImportValue: !Sub ${FihrValidatorStackName}:FHIRValidatorUKCoreLambdaArn
            - snap
        UpdatePrescriptionStatusFunctionArn: !Sub ${UpdatePrescriptionStatusFunctionArn}:$LATEST
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL
      Tracing:
        Enabled: true

  UpdatePrescriptionStatusStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-UpdatePrescriptionStatus
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-UpdatePrescriptionStatus
        AdditionalPolicies: !Join
          - ","
          - - Fn::ImportValue: !Sub ${StackName}:functions:${UpdatePrescriptionStatusFunctionName}:ExecuteLambdaPolicyArn
            - Fn::ImportValue: !Sub ${FihrValidatorStackName}:FHIRValidatorUKCoreExecuteLambdaPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources-pr-290:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources-pr-290:SplunkDeliveryStream

  Format1UpdatePrescriptionsStatusStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-Format1UpdatePrescriptionsStatus
      Type: EXPRESS
      Role: !GetAtt Format1UpdatePrescriptionsStatusStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: Format1UpdatePrescriptionsStatusStateMachine.asl.json
      DefinitionSubstitutions:
        ConvertRequestToFhirFormatFunctionArn: !Sub ${ConvertRequestToFhirFormatFunctionArn}:$LATEST
        UpdatePrescriptionStatusFunctionArn: !Sub ${UpdatePrescriptionStatusFunctionArn}:$LATEST
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt Format1UpdatePrescriptionsStatusStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL
      Tracing:
        Enabled: true

  Format1UpdatePrescriptionsStatusStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-Format1UpdatePrescriptionsStatus
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-Format1UpdatePrescriptionsStatus
        AdditionalPolicies: !Join
          - ","
          - - Fn::ImportValue: !Sub ${StackName}:functions:${ConvertRequestToFhirFormatFunctionName}:ExecuteLambdaPolicyArn
            - Fn::ImportValue: !Sub ${StackName}:functions:${UpdatePrescriptionStatusFunctionName}:ExecuteLambdaPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources-pr-290:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources-pr-290:SplunkDeliveryStream

Outputs:
  UpdatePrescriptionStatusStateMachineArn:
    Description: UpdatePrescriptionStatus state machine arn
    Value: !Ref UpdatePrescriptionStatusStateMachine

  UpdatePrescriptionStatusStateMachineName:
    Description: UpdatePrescriptionStatus state machine name
    Value: !GetAtt UpdatePrescriptionStatusStateMachine.Name

  Format1UpdatePrescriptionsStatusStateMachineArn:
    Description: Format1UpdatePrescriptionsStatus state machine arn
    Value: !Ref Format1UpdatePrescriptionsStatusStateMachine

  Format1UpdatePrescriptionsStatusStateMachineName:
    Description: Format1UpdatePrescriptionsStatus state machine name
    Value: !GetAtt Format1UpdatePrescriptionsStatusStateMachine.Name
