AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU state machines and related resources

Parameters:
  StackName:
    Type: String
    Description: The name of the main stack
    Default: none
  
  UpdatePrescriptionStatusFunctionName:
    Type: String
    Description: The function name of UpdatePrescriptionStatus lambda
    Default: none
  
  UpdatePrescriptionStatusFunctionArn:
    Type: String
    Description: The function ARN of UpdatePrescriptionStatus lambda
    Default: none
  
  LogRetentionInDays:
    Type: Number
    Description: How long to keep logs for
  
  EnableSplunk:
    Type: String
    Description: Whether to use splunk

Resources:
  UpdatePrescriptionStatusStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-UpdatePrescriptionStatus
      Type: EXPRESS
      Role: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: UpdatePrescriptionStatusStateMachine.asl.json
      DefinitionSubstitutions:
        FhirValidationFunctionArn: !Join
          - ":" 
          - - !ImportValue fhir-validator:FHIRValidatorUKCoreLambdaArn
            - snap
        UpdatePrescriptionStatusFunctionArn: !Sub ${UpdatePrescriptionStatusFunctionArn}:$LATEST
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL
  
  UpdatePrescriptionStatusStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-UpdatePrescriptionStatus
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-UpdatePrescriptionStatus
        AdditionalPolicies: !Join
          - ','
          - - Fn::ImportValue: !Sub ${StackName}:functions:${UpdatePrescriptionStatusFunctionName}:ExecuteLambdaPolicyArn
          - - !ImportValue fhir-validator:FHIRValidatorUKCoreExecuteLambdaPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream
  
Outputs:
  UpdatePrescriptionStatusStateMachineArn:
    Description: UpdatePrescriptionStatus state machine arn
    Value: !Ref UpdatePrescriptionStatusStateMachine
  
  UpdatePrescriptionStatusStateMachineName:
    Description: UpdatePrescriptionStatus state machine name
    Value: !GetAtt  UpdatePrescriptionStatusStateMachine.Name
