AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  PSU state machines and related resources

Parameters:
  StackName:
    Type: String
    Default: none

  UpdatePrescriptionStatusFunctionName:
    Type: String
    Default: none

  UpdatePrescriptionStatusFunctionArn:
    Type: String
    Default: none

  UpdatePrescriptionStatusFunctionVersion:
    Type: String
    Default: none

  ConvertRequestToFhirFormatFunctionName:
    Type: String
    Default: none

  ConvertRequestToFhirFormatFunctionArn:
    Type: String
    Default: none

  ConvertRequestToFhirFormatFunctionVersion:
    Type: String
    Default: none

  LogRetentionInDays:
    Type: Number

  EnableSplunk:
    Type: String

  FihrValidatorStackName:
    Type: String
    Default: fhir-validator

Resources:
  UpdatePrescriptionStatusStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-UpdatePrescriptionStatus
      Type: EXPRESS
      Role: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: UpdatePrescriptionStatusStateMachine.asl.json
      DefinitionSubstitutions:
        FhirValidationFunctionArn: !Join
          - ":"
          - - Fn::ImportValue: !Sub ${FihrValidatorStackName}:FHIRValidatorUKCoreLambdaArn
            - snap
        UpdatePrescriptionStatusFunctionArn: !Sub ${UpdatePrescriptionStatusFunctionVersion}
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt UpdatePrescriptionStatusStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL
      Tracing:
        Enabled: true

  UpdatePrescriptionStatusStateMachineVersion:
    Type: "AWS::StepFunctions::StateMachineVersion"
    Properties:
      StateMachineArn: !Ref UpdatePrescriptionStatusStateMachine
      StateMachineRevisionId: !GetAtt UpdatePrescriptionStatusStateMachine.StateMachineRevisionId

  UpdatePrescriptionStatusStateMachineAlias:
    Type: "AWS::StepFunctions::StateMachineAlias"
    Properties:
      Name: prod
      DeploymentPreference:
        StateMachineVersionArn: !Ref UpdatePrescriptionStatusStateMachineVersion
        Type: LINEAR
        Interval: 2
        Percentage: 20
        Alarms:
          - !Ref UpdatePrescriptionStatusStateMachineAlarm

  UpdatePrescriptionStatusStateMachineAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "StepFunctionFailureAlarm"
      AlarmDescription: "Alarm when UpdatePrescriptionStatus Step Function executions fail"
      Namespace: "AWS/States"
      MetricName: "ExecutionsFailed"
      Dimensions:
        - Name: "StateMachineArn"
          Value: !Ref UpdatePrescriptionStatusStateMachine
      Statistic: "Sum"
      Period: 60 # Evaluate every minute
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "notBreaching"

  UpdatePrescriptionStatusStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-UpdatePrescriptionStatus
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-UpdatePrescriptionStatus
        AdditionalPolicies: !Join
          - ","
          - - Fn::ImportValue: !Sub ${StackName}:functions:${UpdatePrescriptionStatusFunctionName}:ExecuteLambdaPolicyArn
            - Fn::ImportValue: !Sub ${FihrValidatorStackName}:FHIRValidatorUKCoreExecuteLambdaPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

  Format1UpdatePrescriptionsStatusStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${StackName}-Format1UpdatePrescriptionsStatus
      Type: EXPRESS
      Role: !GetAtt Format1UpdatePrescriptionsStatusStateMachineResources.Outputs.StateMachineRoleArn
      DefinitionUri: Format1UpdatePrescriptionsStatusStateMachine.asl.json
      DefinitionSubstitutions:
        ConvertRequestToFhirFormatFunctionArn: !Sub ${ConvertRequestToFhirFormatFunctionVersion}
        UpdatePrescriptionStatusFunctionArn: !Sub ${UpdatePrescriptionStatusFunctionVersion}
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt Format1UpdatePrescriptionsStatusStateMachineResources.Outputs.StateMachineLogGroupArn
        IncludeExecutionData: true
        Level: ALL
      Tracing:
        Enabled: true

  Format1UpdatePrescriptionsStatusStateMachineVersion:
    Type: "AWS::StepFunctions::StateMachineVersion"
    Properties:
      StateMachineArn: !Ref Format1UpdatePrescriptionsStatusStateMachine
      StateMachineRevisionId: !GetAtt Format1UpdatePrescriptionsStatusStateMachine.StateMachineRevisionId

  Format1UpdatePrescriptionsStatusStateMachineAlias:
    Type: "AWS::StepFunctions::StateMachineAlias"
    Properties:
      Name: prod
      DeploymentPreference:
        StateMachineVersionArn: !Ref Format1UpdatePrescriptionsStatusStateMachineVersion
        Type: LINEAR
        Interval: 2
        Percentage: 20
        Alarms:
          - !Ref Format1UpdatePrescriptionsStatusStateMachineAlarm

  Format1UpdatePrescriptionsStatusStateMachineAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "StepFunctionFailureAlarm"
      AlarmDescription: "Alarm when Format1UpdatePrescriptions Step Function executions fail"
      Namespace: "AWS/States"
      MetricName: "ExecutionsFailed"
      Dimensions:
        - Name: "StateMachineArn"
          Value: !Ref Format1UpdatePrescriptionsStatusStateMachine
      Statistic: "Sum"
      Period: 60 # Evaluate every minute
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "notBreaching"

  Format1UpdatePrescriptionsStatusStateMachineResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine_resources.yaml
      Parameters:
        StackName: !Ref StackName
        StateMachineName: !Sub ${StackName}-Format1UpdatePrescriptionsStatus
        StateMachineArn: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StackName}-Format1UpdatePrescriptionsStatus
        AdditionalPolicies: !Join
          - ","
          - - Fn::ImportValue: !Sub ${StackName}:functions:${ConvertRequestToFhirFormatFunctionName}:ExecuteLambdaPolicyArn
            - Fn::ImportValue: !Sub ${StackName}:functions:${UpdatePrescriptionStatusFunctionName}:ExecuteLambdaPolicyArn
        LogRetentionInDays: !Ref LogRetentionInDays
        CloudWatchKMSKeyId: !ImportValue account-resources:CloudwatchLogsKmsKeyArn
        EnableSplunk: !Ref EnableSplunk
        SplunkSubscriptionFilterRole: !ImportValue lambda-resources:SplunkSubscriptionFilterRole
        SplunkDeliveryStreamArn: !ImportValue lambda-resources:SplunkDeliveryStream

Outputs:
  UpdatePrescriptionStatusStateMachineArn:
    Description: UpdatePrescriptionStatus state machine arn
    Value: !Ref UpdatePrescriptionStatusStateMachine

  UpdatePrescriptionStatusStateMachineName:
    Description: UpdatePrescriptionStatus state machine name
    Value: !GetAtt UpdatePrescriptionStatusStateMachine.Name

  UpdatePrescriptionStatusStateMachineAlias:
    Description: UpdatePrescriptionStatus state machine alias
    Value: !Ref UpdatePrescriptionStatusStateMachineAlias

  Format1UpdatePrescriptionsStatusStateMachineArn:
    Description: Format1UpdatePrescriptionsStatus state machine arn
    Value: !Ref Format1UpdatePrescriptionsStatusStateMachine

  Format1UpdatePrescriptionsStatusStateMachineName:
    Description: Format1UpdatePrescriptionsStatus state machine name
    Value: !GetAtt Format1UpdatePrescriptionsStatusStateMachine.Name

  Format1UpdatePrescriptionsStatusStateMachineAlias:
    Description: Format1UpdatePrescriptionsStatus state machine name
    Value: !Ref Format1UpdatePrescriptionsStatusStateMachineAlias
