AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  SSM Parameter Store entries. Values may differ between prod and non-prod environments

Parameters:
  StackName:
    Type: String

  Environment:
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]

Resources:
  EnabledSiteODSCodesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyEnabledSiteODSCodes
      Description: "List of site ODS codes for which notifications are enabled"
      Type: String
      Value: !If
        - IsProd
        - > # Prod notification enabled
          FA565
        - > # Non-prod
          FA565

  EnabledSystemsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyEnabledSystems
      Description: "List of application names for which notifications are enabled"
      Type: String
      Value: !If
        - IsProd
        - > # Prod notification enabled
          Apotec Ltd - Apotec CRM - Production,
          CrxPatientApp,
          nhsPrescriptionApp,
          Titan PSU Prod
        - > # Non-prod
          Internal Test System,
          Apotec Ltd - Apotec CRM - Production,
          CrxPatientApp,
          nhsPrescriptionApp,
          Titan PSU Prod

  BlockedSiteODSCodesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyBlockedSiteODSCodes
      Description: "List of site ODS codes for which notifications are blocked"
      Type: String
      Value: !If
        - IsProd
        - > # Prod notification disabled
          B3J1Z
        - > # Non-prod
          B3J1Z

  NotifyRoutingPlanIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyRoutingPlanID
      Description: "Notify Routing Plan ID"
      Type: String
      Value: !If
        - IsProd
        - changeme
        # Non-prod value (sandbox)
        - b838b13c-f98c-4def-93f0-515d4e4f4ee1

  NotifyAPIBaseURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-PSUNotifyApiBaseUrl
      Description: "Notify API Base URL"
      Type: String
      Value: !If
        - IsProd
        - https://api.service.nhs.uk/comms
        # Non-prod API URL (sandbox) (INT environment: https://int.api.service.nhs.uk/comms)
        - https://sandbox.api.service.nhs.uk/comms

  EnableNotificationExternalLink:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-EnableNotificationExternalLink
      Description: "Toggle on or off if we make real requests to the NHS notify service"
      Type: String
      Value: "false"
      
  EnableNotificationsInternal:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${StackName}-EnableNotificationsInternal
      Description: "Toggle the notifications integration entirely"
      Type: String
      Value: "true"

  GetNotificationsParameterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Allows reading SSM parameters"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !GetAtt EnabledSiteODSCodesParameter.Arn
              - !GetAtt EnabledSystemsParameter.Arn
              - !GetAtt BlockedSiteODSCodesParameter.Arn
              - !GetAtt NotifyRoutingPlanIDParameter.Arn
              - !GetAtt NotifyAPIBaseURLParameter.Arn
              - !GetAtt EnableNotificationExternalLink.Arn
              - !GetAtt EnableNotificationsInternal.Arn


Outputs:
  EnabledSiteODSCodesParameterName:
    Description: "Name of the SSM parameter holding enabled site ODS codes"
    Value: !Ref EnabledSiteODSCodesParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyEnabledSiteODSCodesParam

  EnabledSystemsParameterName:
    Description: "Name of the SSM parameter holding enabled system names"
    Value: !Ref EnabledSystemsParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyEnabledSystemsParam

  BlockedSiteODSCodesParameterName:
    Description: "Name of the SSM parameter holding blocked site ODS codes"
    Value: !Ref BlockedSiteODSCodesParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyBlockedSiteODSCodesParam

  NotifyRoutingPlanIDParameterName:
    Description: "Name of the SSM parameter holding the Notify Routing Plan ID"
    Value: !Ref NotifyRoutingPlanIDParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyRoutingPlanIDParam

  NotifyAPIBaseURLParameterName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref NotifyAPIBaseURLParameter
    Export:
      Name: !Sub ${StackName}-PSUNotifyApiBaseUrlParam

  EnableNotificationExternalLinkName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref EnableNotificationExternalLink
    Export:
      Name: !Sub ${StackName}-EnableNotificationExternalLinkName

  EnableNotificationsInternalName:
    Description: "Name of the SSM parameter holding the Notify API Base URL"
    Value: !Ref EnableNotificationsInternal
    Export:
      Name: !Sub ${StackName}-EnableNotificationsInternalName

  GetNotificationsParameterPolicyArn:
    Description: Use kms key policy arn
    Value: !Ref GetNotificationsParameterPolicy
    Export:
      Name: !Sub ${StackName}-GetNotificationsParameterPolicyArn
