AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  SQS messaging stacks used by the PSU

Parameters:
  StackName:
    Type: String

Resources:
  NHSNotifyPrescriptionsSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-NHSNotifyPrescriptions
      KmsMasterKeyId: !ImportValue account-resources:SqsKMSKey
      # TODO: Later, I think 1 day will not be enough. But for now, expiry is the only way to remove messages!
      MessageRetentionPeriod: 86400    # 1 day in seconds
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NHSNotifyPrescriptionsDeadLetterQueue.Arn
        maxReceiveCount: 5
      VisibilityTimeout: 60

  NHSNotifyPrescriptionsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-NHSNotifyPrescriptionsDeadLetter
      KmsMasterKeyId: !ImportValue account-resources:SqsKMSKey
      MessageRetentionPeriod: 604800   # 1 week in seconds
      VisibilityTimeout: 60

  ReadNHSNotifyPrescriptionsSQSQueuePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:ReceiveMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ListQueues
            Resource: !GetAtt NHSNotifyPrescriptionsSQSQueue.Arn

Outputs:
  NHSNotifyPrescriptionsSQSQueueUrl:
    Description: The URL of the NHS Notify Prescriptions SQS Queue
    Value: !Ref NHSNotifyPrescriptionsSQSQueue
    Export:
      Name: !Sub ${AWS::StackName}-NHSNotifyPrescriptionsSQSQueueUrl

  NHSNotifyPrescriptionsSQSQueueArn:
    Description: The ARN of the NHS Notify Prescriptions SQS Queue
    Value: !GetAtt NHSNotifyPrescriptionsSQSQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}-NHSNotifyPrescriptionsSQSQueueArn
