openapi: 3.0.1
info:
  title: "API"
  version: "1.0.0"

paths:
  /:
    post:
      responses:
        x-amazon-apigateway-integration:
          integrationSubtype: "StepFunctions-StartSyncExecution"
          credentials:
            Fn::GetAtt: [HttpApiGatewayResources, Outputs.ApiGwRoleArn]
          requestParameters:
            Input: "$request"
            StateMachineArn: 
              Fn::Sub: ${UpdatePrescriptionStatusStateMachineArn}
          payloadFormatVersion: "1.0"
          type: "aws_proxy"
          connectionType: "INTERNET"

x-amazon-apigateway-importexport-version: "1.0"
