name: package code and api

on:
  workflow_call:
    inputs:
      runtime_docker_image:
        required: true
        type: string
      verify_published_from_main_image:
        type: boolean
        required: true

jobs:
  verify_attestation:
    uses: NHSDigital/eps-common-workflows/.github/workflows/verify-attestation.yml@141907b215220e95e3ed3811d0fe8fa18675dbed
    with:
      runtime_docker_image: "${{ inputs.runtime_docker_image }}"
      verify_published_from_main_image: ${{ inputs.verify_published_from_main_image }}
  package_code_and_api:
    runs-on: ubuntu-22.04
    needs: verify_attestation
    container:
      image: ${{ needs.verify_attestation.outputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setting up .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          echo "@nhsdigital:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Run make install
        run: |
          make install

      - shell: bash
        name: Package code
        run: |
          rm -rf .aws-sam
          export PATH=$PATH:$PWD/node_modules/.bin
          make compile-specification
          make sam-build
          cp Makefile .aws-sam/build/
          cp samconfig_package_and_deploy.toml .aws-sam/build/
          mkdir -p .aws-sam/build/specification
          cp packages/specification/dist/eps-prescription-status-update-api.resolved.json .aws-sam/build/specification/
          cp packages/specification/dist/eps-custom-prescription-status-update-api.resolved.json .aws-sam/build/specification/

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        name: Upload build artifact
        with:
          name: packaged_code
          path: |
            .aws-sam/build
            SAMtemplates/state_machines/UpdatePrescriptionStatusStateMachine.asl.json
            SAMtemplates/state_machines/Format1UpdatePrescriptionsStatusStateMachine.asl.json

      - shell: bash
        name: Package sandbox
        run: |
          rm -rf .aws-sam
          export PATH=$PATH:$PWD/node_modules/.bin
          make compile-specification
          make sam-build-sandbox
          cp Makefile .aws-sam/build/
          cp samconfig_package_and_deploy.toml .aws-sam/build/
          mkdir -p .aws-sam/build/specification
          cp packages/specification/dist/eps-prescription-status-update-api.resolved.json .aws-sam/build/specification/
          cp packages/specification/dist/eps-custom-prescription-status-update-api.resolved.json .aws-sam/build/specification/

      # Readme is included to stop the action flattening the folder structure of aws-sam/build when it is the only item to upload
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        name: Upload sandbox build artifact
        with:
          name: packaged_sandbox_code
          path: |
            .aws-sam/build
            README.md
